---
title: "Metaheuristics"
output: html_document
---


# Load Libraries

```{r}
library(GenSA)
library(ggplot2)
library(GA)
library(dplyr)
```

# Portfolio Optimization

```{r}
library("quantmod")
tickers <- c("GE", "IBM", "GOOG", "AMZN", "AAPL")
getSymbols(tickers, from = "2004-12-01", to = "2018-10-27")
P <- NULL
for(ticker in tickers) {
 tmp <- Cl(to.monthly(eval(parse(text = ticker))))
 P <- cbind(P, tmp)
}
colnames(P) <- tickers
R <- diff(log(P))
R <- R[-1,]
mu <- colMeans(R)
sigma <- cov(R)
library("PerformanceAnalytics")
pContribCVaR <- ES(weights = rep(0.2, 5), method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)$pct_contrib_ES
obj <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out <- tmp1 + 1e3 * tmp2
 return(out)
}
```

# Using GenSA for Simulated Annealing

```{r}
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = obj, lower = rep(0, 5), upper = rep(1, 5), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
cat("GenSA call functions", fn.call.GenSA, "times.\n")
wstar.GenSA <- out.GenSA$par
wstar.GenSA <- wstar.GenSA / sum(wstar.GenSA)
rbind(tickers, round(100 * wstar.GenSA, 2))
100 * (sum(wstar.GenSA * mu) - mean(mu))
```



# Using GA for Genetic Algorithm

```{r}
gap <- ga(type = "real-valued",fitness=function(w) -obj(w),lower=rep(0,5), upper=rep(1,5), popSize = 50, maxiter = 100)
summary(gap)
plot(gap)
```


# Question 2 - Optimal parameters for regression 


```{r}
X <- c(61,63,67,69,70,74,76,81,86,91,95,97)
Y <- c(4.28,4.08,4.42,4.17,4.48,4.3,4.82,4.7,5.11,5.13,5.64,5.56)
k <- data.frame(X = c(61,63,67,69,70,74,76,81,86,91,95,97),Y = c(4.28,4.08,4.42,4.17,4.48,4.3,4.82,4.7,5.11,5.13,5.64,5.56))

regression <- function(a,b)
{
  sum(Y - (a + b*X))^2
}
robj <- function(m)
{
  regression(m[1],m[2])
}
```

# Using GenSA

```{r}
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = robj, lower = rep(0, 2), upper = rep(5, 2), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
b0SA <- out.GenSA$par[1]
b1SA <- out.GenSA$par[2]
cat("GenSA call functions", fn.call.GenSA, "times.\n")
```

# Using GA

```{r}
gap <- ga(type = "real-valued", fitness=function(x)-robj(x), lower=rep(0,2), upper=rep(5,2), popSize = 50, maxiter = 100)
summary(gap)
plot(gap)
```


```{r}
abc <- ggplot(data=k,aes(x=X,y=Y)) + geom_point()
abc <- abc + geom_abline(aes(intercept = b0SA, slope = b1SA, colour = "SA")) +
  geom_abline(aes(intercept = gap@solution[1], slope = gap@solution[2], colour = "GA")) + geom_smooth(method='lm', se =FALSE, aes(colour = "Regression")) + ggtitle("Plot for Regression")
abc <- abc + scale_colour_manual("", values = c("Regression" = "red", "GA" = "green", "SA" = "yellow"))
abc
```
