---
title: "IP_athakur.lp"
output: html_document
---

```{r}
library(lpSolveAPI)
library(data.tree)
z <- read.lp("IP_athakur.lp")
z
```

```{r}
sp1 <- make.lp(0, 2)
set.objfn(sp1, c(-8, -5))
add.constraint(sp1, c(1, 1), "<=", 6)
add.constraint(sp1, c(9, 5), "<=", 45)
RowNames <- c("Labor", "Wood")
ColNames <- c("Tables", "Chairs")
dimnames(sp1) <- list(RowNames, ColNames)
sp1
```

```{r}
write.lp(sp1,'IP_BB.lp',type='lp') # we will use this format soon
solve(sp1)
get.objective(sp1) * -1
get.variables(sp1)
```

```{r}
sp2 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp2, c(-8, -5))
add.constraint(sp2, c(1, 1), "<=", 6)
add.constraint(sp2, c(9, 5), "<=", 45)
add.constraint(sp2,c(1,0),">=",4)
solve(sp2)
get.objective(sp2) * -1
get.variables(sp2)
```
```{r}
sp4 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp4, c(-8, -5))
add.constraint(sp4, c(1, 1), "<=", 6)
add.constraint(sp4, c(9, 5), "<=", 45)
add.constraint(sp4,c(1,0),">=",4)
add.constraint(sp4,c(0,1),">=",2)
solve(sp4)
get.objective(sp4) * -1 # This solution is infeasible
get.variables(sp4)
```
```{r}
sp5 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp5, c(-8, -5))
add.constraint(sp5, c(1, 1), "<=", 6)
add.constraint(sp5, c(9, 5), "<=", 45)
add.constraint(sp5,c(1,0),">=",4)
add.constraint(sp5,c(0,1),"<=",1)
solve(sp5)
get.objective(sp5) * -1 
get.variables(sp5)
```

```{r}
sp6 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp6, c(-8, -5))
add.constraint(sp6, c(1, 1), "<=", 6)
add.constraint(sp6, c(9, 5), "<=", 45)
add.constraint(sp6,c(1,0),">=",5)
add.constraint(sp6,c(0,1),"<=",1)
solve(sp6)
get.objective(sp6) * -1 
get.variables(sp6)
```

```{r}
sp7 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp7, c(-8, -5))
add.constraint(sp7, c(1, 1), "<=", 6)
add.constraint(sp7, c(9, 5), "<=", 45)
add.constraint(sp7,c(1,0),"<=",4)
add.constraint(sp7,c(0,1),"<=",1)
solve(sp7)
get.objective(sp7) * -1 
get.variables(sp7)
```
```{r}
sp3 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp3, c(-8, -5))
add.constraint(sp3, c(1, 1), "<=", 6)
add.constraint(sp3, c(9, 5), "<=", 45)
add.constraint(sp3,c(1,0),"<=",3)
solve(sp3)
get.objective(sp3) * -1
get.variables(sp3)
```

```{r}
sp8 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp8, c(-8, -5))
add.constraint(sp8, c(1, 1), "<=", 6)
add.constraint(sp8, c(9, 5), "<=", 45)
add.constraint(sp8,c(0,1),"<=",2)
solve(sp8)
get.objective(sp8) * -1
get.variables(sp8)
```

```{r}
sp9 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp9, c(-8, -5))
add.constraint(sp9, c(1, 1), "<=", 6)
add.constraint(sp9, c(9, 5), "<=", 45)
add.constraint(sp9,c(0,1),"=",2)
add.constraint(sp9,c(1,0),">=",4)
solve(sp9)
get.objective(sp9) * -1
get.variables(sp9)
```
```{r}
sp10 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp10, c(-8, -5))
add.constraint(sp10, c(1, 1), "<=", 6)
add.constraint(sp10, c(9, 5), "<=", 45)
add.constraint(sp10,c(0,1),"=",2)
add.constraint(sp10,c(1,0),"<=",3)
solve(sp10)
get.objective(sp10) * -1
get.variables(sp10)
```

```{r}
sp11 <- make.lp(0, 2) # number of constraints, number of decision variables
set.objfn(sp11, c(-8, -5))
add.constraint(sp11, c(1, 1), "<=", 6)
add.constraint(sp11, c(9, 5), "<=", 45)
add.constraint(sp11,c(0,1),">=",3)
solve(sp11)
get.objective(sp11) * -1
get.variables(sp11)

```

```{r}

library(data.tree)


integerprogram <- Node$new("X1 = 3.75, X2 = 2.25, Z = 41.25")

branch1 <- integerprogram$AddChild("Branch X1")
sp3 <- branch1$AddChild("if X1 <= 3, X1 = 3, X2 = 3, then Z = 39")
sp2 <- branch1$AddChild("if X1 >= 4, X1 = 4, X2 = 1.8, then Z = 41")
subbranch1 <- sp2$AddChild("Branch X2")
sp5 <- subbranch1$AddChild("if X2 <= 1, X1 = 4.44, X2 = 1, then Z = 40.56")
subbranch2 <- sp5$AddChild("Branch X1")
sp7 <- subbranch2$AddChild("if X1 <= 4, X1 = 4, X2 = 1, then Z = 37")
sp6 <- subbranch2$AddChild("if X1 >= 5, X1 = 5, X2 = 0, then Z = 40")
sp4 <- subbranch1$AddChild("if X2 >= 2, X1 = 0.000000e+00, X2 = 1.235164e-322, then Z = -1e+30")

branch2 <- integerprogram$AddChild("Branch X2")
sp8 <- branch2$AddChild("if X2 <= 2, X1 = 3.88, X2 = 2, then Z = 41.11")
subbranch3 <- sp8$AddChild("Branch X1")
sp10 <- subbranch3$AddChild("if X1 <= 3, X1 = 3, X2 = 2, then Z = 34")
sp9 <- subbranch3$AddChild("if X1 >= 4, X1 = 2.121996e-314, X2 = 2.121996e-314, then Z = -1e+30")
sp11 <- branch2$AddChild("if X2 >= 3, X1 = 3, X2 = 3, then Z = 39")

print(integerprogram)
```
